version: '3.1'
services:
  db:
    container_name: mysql5_7
    command: --default-authentication-plugin=mysql_native_password
    image: mysql:5.7
    ports:
      - 3306:3306
    volumes:
      - ./dbdata:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456